In [151]:
import torch
import numpy as np

inputs=np.array([[73,67,43],
                 [91,88,64],
                 [87,134,58],
                 [102,43,37],
                 [69,96,70]],dtype='float32')

targets=np.array([[56,70],
                  [81,101],
                  [119,133],
                  [22,37],
                  [103,119]],dtype='float32')

print(inputs)
print(targets)

inputs=torch.from_numpy(inputs)
targets=torch.from_numpy(targets)
print(inputs)
print(targets)

w=torch.randn(2,3,requires_grad=True)
b=torch.randn(2,requires_grad=True)

print(w)
print(b)




[[ 73.  67.  43.]
 [ 91.  88.  64.]
 [ 87. 134.  58.]
 [102.  43.  37.]
 [ 69.  96.  70.]]
[[ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]]
tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])
tensor([[ 1.4392, -1.7476, -0.2862],
        [-1.9202, -0.6233, -1.2183]], requires_grad=True)
tensor([-0.2411, -1.1455], requires_grad=True)


In [152]:
def linear_model(x):
   return x @ w.t() +b

In [153]:
preds=linear_model(inputs)
print(preds)

tensor([[ -24.5737, -235.4651],
        [ -41.3780, -308.7016],
        [-125.8074, -322.3825],
        [  60.8245, -268.8809],
        [ -88.7398, -278.7542]], grad_fn=<AddBackward0>)


In [154]:
diff=preds-targets
torch.sum(diff*diff)/diff.numel()


tensor(83997.9688, grad_fn=<DivBackward0>)

In [155]:
def mse(t1,t2):
    diff=t1-t2
    return torch.sum(diff*diff)/diff.numel()

In [156]:
loss=mse(preds,targets)


print(loss)

tensor(83997.9688, grad_fn=<DivBackward0>)


In [157]:

loss.backward()

print(w.grad)

tensor([[ -9517.2939, -13141.8926,  -7496.1938],
        [-31568.9922, -33775.6875, -20985.6953]])


In [158]:
with torch.no_grad():
    w-=w.grad*1e-5
    b-=b.grad*1e-5

In [159]:
w,b

(tensor([[ 1.5344, -1.6162, -0.2113],
         [-1.6045, -0.2855, -1.0085]], requires_grad=True),
 tensor([-0.2399, -1.1417], requires_grad=True))

In [160]:
preds=linear_model(inputs)
loss=mse(preds,targets)
print(loss)

tensor(57614.7422, grad_fn=<DivBackward0>)


In [161]:
preds=linear_model(inputs)
print(preds)

tensor([[  -5.5965, -180.7624],
        [ -16.3536, -236.8166],
        [ -95.5682, -237.4826],
        [  78.9579, -214.3885],
        [ -64.3081, -209.8532]], grad_fn=<AddBackward0>)


In [162]:
loss=mse(preds,targets)
print(loss)

tensor(57614.7422, grad_fn=<DivBackward0>)


In [163]:
loss.backward()
print(w.grad)
print(b.grad)

tensor([[-17068.8359, -24153.6152, -13681.8652],
        [-57491.2812, -61486.3359, -38228.1250]])
tensor([-216.9086, -682.6975])


In [164]:
with torch.no_grad():
    w-=w.grad*1e-5
    b-=b.grad*1e-5
    w.grad.zero_()
    b.grad.zero_()

In [165]:
print(w)
print(b)

tensor([[ 1.7051, -1.3747, -0.0745],
        [-1.0296,  0.3293, -0.6262]], requires_grad=True)
tensor([-0.2378, -1.1349], requires_grad=True)


In [166]:
preds=linear_model(inputs)
loss=mse(preds,targets)
print(loss)

tensor(22876.0645, grad_fn=<DivBackward0>)


In [167]:
for i in range(100):
    preds=linear_model(inputs)
    loss=mse(preds,targets)
    loss.backward()
    with torch.no_grad():
        w-=w.grad*1e-5
        b-=b.grad*1e-5
        w.grad.zero_()
        b.grad.zero_()
    

In [168]:
print(loss)

tensor(914.0900, grad_fn=<DivBackward0>)


In [170]:
preds

tensor([[ 70.3862,  70.3661],
        [ 90.0709,  93.6691],
        [ 79.5523, 148.7859],
        [ 98.0511,  37.7303],
        [ 70.6370, 106.3193]], grad_fn=<AddBackward0>)

In [171]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [172]:
import torch.nn as nn
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70], 
                   [74, 66, 43], 
                   [91, 87, 65], 
                   [88, 134, 59], 
                   [101, 44, 37], 
                   [68, 96, 71], 
                   [73, 66, 44], 
                   [92, 87, 64], 
                   [87, 135, 57], 
                   [103, 43, 36], 
                   [68, 97, 70]], 
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119],
                    [57, 69], 
                    [80, 102], 
                    [118, 132], 
                    [21, 38], 
                    [104, 118], 
                    [57, 69], 
                    [82, 100], 
                    [118, 134], 
                    [20, 38], 
                    [102, 120]], 
                   dtype='float32')

inputs=torch.from_numpy(inputs)
targets=torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 74.,  66.,  43.],
        [ 91.,  87.,  65.],
        [ 88., 134.,  59.],
        [101.,  44.,  37.],
        [ 68.,  96.,  71.],
        [ 73.,  66.,  44.],
        [ 92.,  87.,  64.],
        [ 87., 135.,  57.],
        [103.,  43.,  36.],
        [ 68.,  97.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])


In [173]:
from torch.utils.data import TensorDataset

train_ds=TensorDataset(inputs,targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [174]:
from torch.utils.data import DataLoader

batch_size=5
train_dl=DataLoader(train_ds,batch_size,shuffle=True)

In [176]:
for xb,yb in train_dl:
    print(xb)
    print(yb)
    break

tensor([[ 69.,  96.,  70.],
        [102.,  43.,  37.],
        [ 73.,  66.,  44.],
        [101.,  44.,  37.],
        [ 91.,  88.,  64.]])
tensor([[103., 119.],
        [ 22.,  37.],
        [ 57.,  69.],
        [ 21.,  38.],
        [ 81., 101.]])


In [177]:
model=nn.Linear(3,2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.3932,  0.1160,  0.5591],
        [-0.3739,  0.5694,  0.4751]], requires_grad=True)
Parameter containing:
tensor([-0.5479,  0.4655], requires_grad=True)


In [183]:
list(model.parameters())

[Parameter containing:
 tensor([[-0.3932,  0.1160,  0.5591],
         [-0.3739,  0.5694,  0.4751]], requires_grad=True),
 Parameter containing:
 tensor([-0.5479,  0.4655], requires_grad=True)]

In [184]:
preds=model(inputs)
print(preds)

tensor([[  2.5586,  31.7517],
        [  9.6575,  46.9566],
        [ 13.2110,  71.7957],
        [-14.9839,   4.3914],
        [ 22.5916,  62.5886],
        [  2.0494,  30.8084],
        [ 10.1007,  46.8623],
        [ 13.3769,  71.8969],
        [-14.4747,   5.3347],
        [ 23.5440,  63.4376],
        [  3.0017,  31.6574],
        [  9.1483,  46.0133],
        [ 12.7679,  71.8901],
        [-15.9363,   3.5424],
        [ 23.1008,  63.5320]], grad_fn=<AddmmBackward0>)


In [185]:
import torch.nn.functional as F

loss_fn=F.mse_loss
loss=loss_fn(model(inputs),targets)
print(loss)

tensor(3914.6650, grad_fn=<MseLossBackward0>)


In [188]:
opt=torch.optim.SGD(model.parameters(),lr=1e-5)

In [189]:
def fit(num_epochs,model,loss_fn,opt,train_dl):
    for epoch in range(num_epochs):
        for xb,yb in train_dl:
            pred=model(xb)
            loss=loss_fn(pred,yb)
            loss.backward()
            opt.step()
            opt.zero_grad()

        if (epoch+1)%10==0:
            print("epoch [{}/{}],Loss:{:.4f}".format(epoch+1,num_epochs,loss.item()))

In [190]:
fit(100,model,loss_fn,opt,train_dl)

epoch [10/100],Loss:54.7072
epoch [20/100],Loss:62.0109
epoch [30/100],Loss:46.0369
epoch [40/100],Loss:27.3191
epoch [50/100],Loss:23.6295
epoch [60/100],Loss:12.9777
epoch [70/100],Loss:5.9922
epoch [80/100],Loss:12.8165
epoch [90/100],Loss:5.3335
epoch [100/100],Loss:2.6715
